In [1]:
import pandas as pd

In [2]:
csv_file = "../files/issues.csv"  
df = pd.read_csv(csv_file)

In [4]:
df.head()

,number,database,rewrite_type,issue_url,source_query,dest_query
0,2,discourse,Predicate Elimination,https://github.com/discourse/discourse/commit/...,SELECT * FROM posts LEFT JOIN topic_allowed_gr...,SELECT * FROM posts LEFT JOIN topic_allowed_gr...
1,3,discourse,DISTINCT elimination,https://github.com/discourse/discourse/commit/...,SELECT DISTINCT * FROM child_themes WHERE pare...,SELECT * FROM child_themes WHERE parent_theme_...
2,4,discourse,Subquery to join,https://github.com/discourse/discourse/commit/...,SELECT posts.* FROM posts INNER JOIN topics ON...,SELECT posts.* FROM posts INNER JOIN (SELECT t...
3,5,discourse,OR to union,https://github.com/discourse/discourse/commit/...,SELECT * FROM posts WHERE topic_id = 6020 AND ...,SELECT * FROM posts WHERE id IN ((SELECT posts...
4,6,discourse,Subquery to predicate,https://github.com/discourse/discourse/commit/...,SELECT * FROM posts INNER JOIN topics ON topic...,SELECT * FROM posts INNER JOIN topics ON topic...

In [5]:
for _, row in df.iterrows():
    filename = f"../query/{row['database']}_{row['number']}.sql"
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write(row["source_query"])
    
    print(f"Saved: {filename}")

Saved: ../query/discourse_2.sql
Saved: ../query/discourse_3.sql
Saved: ../query/discourse_4.sql
Saved: ../query/discourse_5.sql
Saved: ../query/discourse_6.sql
Saved: ../query/discourse_7.sql
Saved: ../query/discourse_8.sql
Saved: ../query/discourse_10.sql
Saved: ../query/discourse_11.sql
Saved: ../query/discourse_12.sql
Saved: ../query/discourse_13.sql
Saved: ../query/discourse_14.sql
Saved: ../query/discourse_15.sql
Saved: ../query/discourse_17.sql
Saved: ../query/discourse_18.sql
Saved: ../query/gitlab_19.sql
Saved: ../query/gitlab_21.sql
Saved: ../query/gitlab_22.sql
Saved: ../query/gitlab_23.sql
Saved: ../query/gitlab_24.sql
Saved: ../query/gitlab_25.sql
Saved: ../query/gitlab_26.sql
Saved: ../query/gitlab_27.sql
Saved: ../query/gitlab_28.sql
Saved: ../query/gitlab_29.sql
Saved: ../query/gitlab_30.sql
Saved: ../query/gitlab_31.sql
Saved: ../query/gitlab_32.sql
Saved: ../query/gitlab_34.sql
Saved: ../query/gitlab_35.sql
Saved: ../query/gitlab_37.sql
Saved: ../query/gitlab_39.sql
Saved: ../query/gitlab_40.sql
Saved: ../query/gitlab_41.sql
Saved: ../query/gitlab_42.sql
Saved: ../query/gitlab_43.sql
Saved: ../query/gitlab_44.sql
Saved: ../query/gitlab_45.sql
Saved: ../query/gitlab_46.sql
Saved: ../query/gitlab_47.sql
Saved: ../query/spree_50.sql
Saved: ../query/spree_51.sql
Saved: ../query/spree_53.sql
Saved: ../query/spree_54.sql
Saved: ../query/diaspora_57.sql
Saved: ../query/redmine_64.sql
Saved: ../query/redmine_65.sql
Saved: ../query/solidus_79.sql
Saved: ../query/lobsters_88.sql
Saved: ../query/lobsters_134.sql